# ===== IMAXE NGINX =====
# Usa imaxe oficial de Nginx con Alpine Linux (moi lixeira)
FROM nginx:alpine

# Crea directorios para arquivos statics
# (preparados para futuras páxinas de erro personalizadas e imaxes)
RUN mkdir -p /usr/share/nginx/error_pages
RUN mkdir -p /usr/share/nginx/html/assets/images

# Copia as páxinas de erro personalizadas
COPY src/main/resources/static/error_pages /usr/share/nginx/error_pages

# Copia a miña configuración personalizada de Nginx
# Reemplaza a configuración por defecto
COPY nginx.conf /etc/nginx/conf.d/default.conf
